### ISSUE TITLE
Reading multiple log lines from a single buffer

### ISSUE THREAD

**Issue by DanielHeath** [jeromer/syslogparser#15]
I can repeatedly call `Parse()` and `Dump()` and it looks like it'll work, but it'd be nice to be able to read out multiple lines.

**Comment by jeromer** [comment]
For Python/Java stack traces for example ?

**Comment by DanielHeath** [comment]
Yeah - there's plenty of cases where a single buffer will hold multiple lines, and it's something easy to get wrong as a library consumer.

**Comment by jeromer** [comment]
Hi Daniel,

On Sat, Jun 23, 2018, at 1:29 AM, Daniel Heath wrote:
> Yeah - there's plenty of cases where a single buffer will hold
> multiple lines, and it's something easy to get wrong as a library
> consumer.
As far as I can remember the syslog specs (both 3164 and 5424) do not
support multiline logs. I need to double check this though.
Maybe this would be the time for a parser v2 with more tolerance over
malformed lines and more control over what to parse and how to parse.
Will think about this when I have a moment.

Thanks :)
