### ISSUE TITLE
Parsing issue

### ISSUE THREAD

**Issue by fallais** [jeromer/syslogparser#20]
Hello,
this kind of log is not parsed : `<15> Sep 12 16:53:56 XXXTR555 This is a log`.
Is it because of the space ?

**Comment by jeromer** [comment]
Yes, it's because of the extra space between the priority and timestamp fields. Hopefully I fixed the issue in 9059bc5 but this log line is missing a tag which means that `This` will most likely be interpreted as a tag and `is a log` as the message.
