### ISSUE TITLE
Parsing of time appears to be contrary to RFC3164

### ISSUE THREAD

**Issue by abligh** [jeromer/syslogparser#6]
RFC3164 states (at 4.1.2):

> The TIMESTAMP field is the *local* time and is in the format of "Mmm dd hh:mm:ss" (without the quote marks)

(my emphasis). `rfc3164.go` has the following code

    ts, err = time.Parse(tsFmt, string(sub))

The documentation for `time.Parse` says:

> In the absence of a time zone indicator, `Parse` returns a time in UTC.

If the local time of the syslog origin is not UTC, this will return an erroneous time. Using the local timezone of the syslog server interpreting the information is also incorrect, as that could be different from the local timezone of the syslog client. Obviously this is really a defect in the syslog protocol and sane people would set all their local timezones (for syslog purposes) to UTC, but apparently not everyone is sane.

It would therefore be useful to be able to specify the 'local' timezone of the server to the parser; if this is set, use `time.ParseInLocation()` else (as currently) use `Parse()`.

I think this should be unnecessary for RFC5424 parsing.

**Comment by jeromer** [comment]
> It would therefore be useful to be able to specify the 'local' timezone of the server to the parser; if this is set, use time.ParseInLocation() else (as currently) use Parse().

Sounds like a good idea to me. Could you please provide a patch ?

Thanks :)

**Comment by abligh** [comment]
See pull request #7
