### ISSUE TITLE
Panic in rfc3164.go L192

### ISSUE THREAD

**Issue by Xiol** [jeromer/syslogparser#9]
Hi,

I'm using go-syslog (which imports this package) to receive logs from installing servers. I'm seeing a panic originating from rfc3164.go on line 192 when a blank message (?) arrives.

Here's a tcpdump:

```
11:32:09.659220 IP (tos 0x0, ttl 64, id 21646, offset 0, flags [DF], proto UDP (17), length 101)
    192.168.1.187.61000 > 192.168.1.5.5514: UDP, length 73
E..eT.@.@.a..........H...Q.
<13>Mar 18 11:32:10 log-output: HTTP request sent, awaiting response... 

11:32:09.666068 IP (tos 0x0, ttl 64, id 21647, offset 0, flags [DF], proto UDP (17), length 78)
    192.168.1.187.61000 > 192.168.1.5.5514: UDP, length 50
E..NT.@.@.a..........H...:.N<13>Mar 18 11:32:10 log-output: No data received.

11:32:09.666343 IP (tos 0x0, ttl 64, id 21648, offset 0, flags [DF], proto UDP (17), length 70)
    192.168.1.187.61000 > 192.168.1.5.5514: UDP, length 42
E..FT.@.@.b..........H...2..<13>Mar 18 11:32:10 log-output: Retrying.

11:32:09.666360 IP (tos 0x0, ttl 64, id 21649, offset 0, flags [DF], proto UDP (17), length 61)
    192.168.1.187.61000 > 192.168.1.5.5514: UDP, length 33
E..=T.@.@.b..........H...)..<13>Mar 18 11:32:10 log-output: 
```

In this example, the first three entries are parsed fine, but the last one causes the panic (paths truncated)

```
panic: runtime error: index out of range
goroutine 9 [running]:
panic(0xa68880, 0xc82000e020)
/.../build/go/src/runtime/panic.go:464 +0x3e6
.../github.com/jeromer/syslogparser/rfc3164.(*Parser).parseTag(0xc8200e4aa0, 0x0, 0x0, 0x0, 0x0)
/.../github.com/jeromer/syslogparser/rfc3164/rfc3164.go:192 +0x214
.../github.com/jeromer/syslogparser/rfc3164.(*Parser).parsemessage(0xc8200e4aa0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
.../github.com/jeromer/syslogparser/rfc3164/rfc3164.go:109 +0x78
.../github.com/jeromer/syslogparser/rfc3164.(*Parser).Parse(0xc8200e4aa0, 0x0, 0x0)
.../github.com/jeromer/syslogparser/rfc3164/rfc3164.go:56 +0x130
.../gopkg.in/mcuadros/go-syslog%2ev2.(*Server).parser(0xc820536240, 0xc8209c4000, 0x2a, 0x10000, 0xc82083dd00, 0x1
.../gopkg.in/mcuadros/go-syslog.v2/server.go:248 +0x92
.../gopkg.in/mcuadros/go-syslog%2ev2.(*Server).goParseDatagrams.func1(0xc820536240)
.../gopkg.in/mcuadros/go-syslog.v2/server.go:363 +0x282
created by .../gopkg.in/mcuadros/go-syslog%2ev2.(*Server).goParseDatagrams
.../gopkg.in/mcuadros/go-syslog.v2/server.go:367 +0x92
```

Thanks

**Comment by Xiol** [comment]
I originally thought that this might happen on a blank message, but I think it happens when the message itself is just one word long, as it tries to parse it as a tag and panics when it doesn't find the end and keeps incrementing the cursor.

I went the naive route and added a load of Printf statements to parseTag(). Here's two successful parses and a failure:

```
myapp[5394]: in parsetag cursor 32 - len 38
myapp[5394]: line: <13>Mar 18 12:32:25 log-output: 200 OK
myapp[5394]: in loop p.cursor: 32
myapp[5394]: doing byte: 2
myapp[5394]: in loop p.cursor: 33
myapp[5394]: doing byte: 0
myapp[5394]: in loop p.cursor: 34
myapp[5394]: doing byte: 0
myapp[5394]: in loop p.cursor: 35
myapp[5394]: doing byte:
myapp[5394]: eot - found?: true
myapp[5394]: done with line: <13>Mar 18 12:32:25 log-output: 200 OK
myapp[5394]: tag: 200
myapp[5394]: in parsetag cursor 32 - len 40
myapp[5394]: line: <13>Mar 18 12:32:25 log-output: Length:
myapp[5394]: in loop p.cursor: 32
myapp[5394]: doing byte: L
myapp[5394]: in loop p.cursor: 33
myapp[5394]: doing byte: e
myapp[5394]: in loop p.cursor: 34
myapp[5394]: doing byte: n
myapp[5394]: in loop p.cursor: 35
myapp[5394]: doing byte: g
myapp[5394]: in loop p.cursor: 36
myapp[5394]: doing byte: t
myapp[5394]: in loop p.cursor: 37
myapp[5394]: doing byte: h
myapp[5394]: in loop p.cursor: 38
myapp[5394]: doing byte: :
myapp[5394]: eot - found?: true
myapp[5394]: space
myapp[5394]: done with line: <13>Mar 18 12:32:25 log-output: Length:
myapp[5394]: tag: Length
myapp[5394]: in parsetag cursor 32 - len 34
myapp[5394]: line: <13>Mar 18 12:32:25 log-output: 15
myapp[5394]: in loop p.cursor: 32
myapp[5394]: doing byte: 1
myapp[5394]: in loop p.cursor: 33
myapp[5394]: doing byte: 5
myapp[5394]: in loop p.cursor: 34
myapp[5394]: panic: runtime error: index out of range
myapp[5394]: goroutine 35 [running]:
myapp[5394]: panic(0xa691c0, 0xc82000e020)
```

**Comment by Xiol** [comment]
Have opened MR #10 which seems to fix the issue in my testing.

**Comment by eenblam** [comment]
@jeromer I just confirmed the same.

In particular:
- `<13>Mar 18 11:32:10 log-output: ` panics
- `<13>Mar 18 11:32:10 log-output: asdf` panics
- `<13>Mar 18 11:32:10 log-output: asdf ` doesn't panic but instead fails because it
    1. thinks `"log-output:"` is the hostname
    2. thinks `"asdf"` is the tag
    3. thinks `" "` is the content

**Comment by eenblam** [comment]
## Probably missing hostname, not tag
@Xiol Can you confirm that `log-output` was indeed a hostname and not a tag instead? The latter situation (i.e. a tag) seems more likely to have occurred from an RFC3164-compliant client.

1. Hostnames should only be ASCII lowercase letters, digits, or underscores, excluding `:`.
2. From [section 4.1.2](https://tools.ietf.org/html/rfc3164#section-4.1.2): 
> The TIMESTAMP will immediately follow the trailing ">" from the PRI
   part and single space characters MUST follow each of the TIMESTAMP
   **and HOSTNAME** fields.
   ...
   ...A single space character MUST also follow the HOSTNAME field.
3. From [section 4.1.3](https://tools.ietf.org/html/rfc3164#section-4.1.3):
> Most commonly, the first character of the CONTENT field that signifies the 
   conclusion of the TAG field has been seen to be the left square
   bracket character ("["), a colon character (":"), or a space
   character.

If you know your client isn't setting a hostname, this can be mitigated by doing something like this:
```go
p := NewParser(buff)
p.Hostname("whatever")
err := p.Parse()
```
See `parseHostname()` in `rfc3164/rfc3164.go` for why.

On the other hand, tags should only contain ASCII characters, unless they specify a PID, e.g. `sshd[24521]`. Seems like you have a funky client or relay in the mix there.

## Parser is broken regardless
That said, the parser shouldn't be breaking on the above test cases. In particular, the parser should *always* be able to parse a record lacking a hostname, lacking a tag, lacking both, etc.

@jeromer I'll look into how this can be mitigated.
